import '../../features/dashboard/data/models/movie_model.dart';

/// Pre-configured high-resolution movie dataset for mock screens and offline fallback.
class MockData {
  MockData._();

  static final List<MovieModel> sampleMovies = [
    const MovieModel(
      id: 101,
      title: 'Dune: Part Two',
      overview: 'Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.',
      posterPath: 'https://image.tmdb.org/t/p/w500/1pdfLPoLStVJozStmKzpTKWio25.jpg',
      backdropPath: 'https://image.tmdb.org/t/p/original/xOMo8ScSu22B2v8sL5WBbg2WWhE.jpg',
      voteAverage: 8.5,
      releaseDate: '2024-03-01',
      genres: ['Sci-Fi', 'Adventure', 'Action'],
      runtime: 166,
      status: 'Released',
    ),
    const MovieModel(
      id: 102,
      title: 'Oppenheimer',
      overview: 'The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.',
      posterPath: 'https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGvC2gu1Wv9.jpg',
      backdropPath: 'https://image.tmdb.org/t/p/original/fm6K8StfiRo2Z2C8y9V0G9nWWhE.jpg',
      voteAverage: 8.9,
      releaseDate: '2023-07-21',
      genres: ['Drama', 'History', 'Biography'],
      runtime: 180,
      status: 'Released',
    ),
    const MovieModel(
      id: 103,
      title: 'Interstellar',
      overview: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
      posterPath: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
      backdropPath: 'https://image.tmdb.org/t/p/original/rAiYTfKGqDCRIIqo6LEuPJjZz8B.jpg',
      voteAverage: 8.7,
      releaseDate: '2014-11-07',
      genres: ['Sci-Fi', 'Drama', 'Adventure'],
      runtime: 169,
      status: 'Released',
    ),
    const MovieModel(
      id: 104,
      title: 'The Dark Knight',
      overview: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological tests.',
      posterPath: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
      backdropPath: 'https://image.tmdb.org/t/p/original/nMK4812RiBhHCG2K9Su5CRHw0pE.jpg',
      voteAverage: 9.0,
      releaseDate: '2008-07-18',
      genres: ['Action', 'Crime', 'Drama'],
      runtime: 152,
      status: 'Released',
    ),
    const MovieModel(
      id: 105,
      title: 'Avatar: The Way of Water',
      overview: 'Jake Sully lives with his newfound family formed on the extrasolar moon Pandora. Once a familiar threat returns, Jake must work with Neytiri.',
      posterPath: 'https://image.tmdb.org/t/p/w500/t6HIw3zMMGlUZFiYIGB8ScABvWK.jpg',
      backdropPath: 'https://image.tmdb.org/t/p/original/vL5LR6WvyjGfdCkgOIZWSpYWug7.jpg',
      voteAverage: 7.7,
      releaseDate: '2022-12-16',
      genres: ['Sci-Fi', 'Action', 'Adventure'],
      runtime: 192,
      status: 'Released',
    ),
    const MovieModel(
      id: 106,
      title: 'Spider-Man: Across the Spider-Verse',
      overview: 'Miles Morales is catapulted across the Multiverse, where he encounters a team of Spider-People charged with protecting its very existence.',
      posterPath: 'https://image.tmdb.org/t/p/w500/8Vt6mWEReuy4Of61Lnj5Xj7sFm8.jpg',
      backdropPath: 'https://image.tmdb.org/t/p/original/4Hod2vLwbv44O6mR1g85G4b6WWhE.jpg',
      voteAverage: 8.4,
      releaseDate: '2023-06-02',
      genres: ['Animation', 'Action', 'Adventure'],
      runtime: 140,
      status: 'Released',
    ),
  ];

  static final List<MovieModel> upcomingMovies = [
    const MovieModel(
      id: 201,
      title: 'Deadpool & Wolverine',
      overview: 'Wolverine is recovering from his injuries when he crosses paths with the loudmouth Deadpool.',
      posterPath: 'https://image.tmdb.org/t/p/w500/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg',
      backdropPath: 'https://image.tmdb.org/t/p/original/yDHYTfA3R0jFYba16jBB12M2w0X.jpg',
      voteAverage: 7.9,
      releaseDate: '2026-07-26',
      genres: ['Action', 'Comedy', 'Sci-Fi'],
    ),
    const MovieModel(
      id: 202,
      title: 'Gladiator II',
      overview: 'Years after witnessing the death of Maximus, Lucius enters the Colosseum after his home is conquered.',
      posterPath: 'https://image.tmdb.org/t/p/w500/2cxhvwyEwRlysAmRH4iodkvo0z5.jpg',
      backdropPath: 'https://image.tmdb.org/t/p/original/3V4kStf6v27b4B8L00pP71M2w0X.jpg',
      voteAverage: 7.5,
      releaseDate: '2026-11-22',
      genres: ['Action', 'Drama', 'Adventure'],
    ),
    const MovieModel(
      id: 203,
      title: 'Wicked: Part One',
      overview: 'Elphaba, a misunderstood young woman because of her green skin, meets Glinda, a popular blonde.',
      posterPath: 'https://image.tmdb.org/t/p/w500/v9Q61sF6z3G6b6M8wL12M2w0X.jpg',
      backdropPath: 'https://image.tmdb.org/t/p/original/u2B82kStf5v27b4B8L00pP71M2w0X.jpg',
      voteAverage: 8.0,
      releaseDate: '2026-11-27',
      genres: ['Fantasy', 'Musical', 'Drama'],
    ),
  ];
}
