import '../../features/dashboard/data/models/movie_model.dart';

/// Pre-configured high-resolution movie dataset for mock screens and offline fallback.
class MockData {
  MockData._();

  static final List<MovieModel> sampleMovies = [
    const MovieModel(
      id: 101,
      title: 'Dune: Part Two',
      overview: 'Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.',
      posterPath: 'https://image.tmdb.org/t/p/w500/1pdfLvkJqssohUaN8x5O1fJ2J9B.jpg',
      backdropPath: 'https://image.tmdb.org/t/p/original/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg',
      voteAverage: 8.5,
      releaseDate: '2024-03-01',
      genres: ['Sci-Fi', 'Adventure', 'Action'],
      runtime: 166,
      status: 'Released',
    ),
    const MovieModel(
      id: 102,
      title: 'Oppenheimer',
      overview: 'The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.',
      posterPath: 'https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
      backdropPath: 'https://image.tmdb.org/t/p/original/nb3xI8XI3w4pMVZ38VijbsyBqP4.jpg',
      voteAverage: 8.9,
      releaseDate: '2023-07-21',
      genres: ['Drama', 'History', 'Biography'],
      runtime: 180,
      status: 'Released',
    ),
    const MovieModel(
      id: 103,
      title: 'Interstellar',
      overview: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
      posterPath: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
      backdropPath: 'https://image.tmdb.org/t/p/original/pbrkL804c8yAv3zBZR4QPEafpAR.jpg',
      voteAverage: 8.7,
      releaseDate: '2014-11-07',
      genres: ['Sci-Fi', 'Drama', 'Adventure'],
      runtime: 169,
      status: 'Released',
    ),
    const MovieModel(
      id: 104,
      title: 'The Dark Knight',
      overview: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological tests.',
      posterPath: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haP0PHD.jpg',
      backdropPath: 'https://image.tmdb.org/t/p/original/dqK9Hag1054tghRQSqLSfrkvQnA.jpg',
      voteAverage: 9.0,
      releaseDate: '2008-07-18',
      genres: ['Action', 'Crime', 'Drama'],
      runtime: 152,
      status: 'Released',
    ),
    const MovieModel(
      id: 105,
      title: 'Avatar: The Way of Water',
      overview: 'Jake Sully lives with his newfound family formed on the extrasolar moon Pandora. Once a familiar threat returns, Jake must work with Neytiri.',
      posterPath: 'https://image.tmdb.org/t/p/w500/t6HIqrRAclMCA60VSmeqeLUDBA.jpg',
      backdropPath: 'https://image.tmdb.org/t/p/original/sbXMNAqS2t721pS7GZ429wP1t1W.jpg',
      voteAverage: 7.7,
      releaseDate: '2022-12-16',
      genres: ['Sci-Fi', 'Action', 'Adventure'],
      runtime: 192,
      status: 'Released',
    ),
    const MovieModel(
      id: 106,
      title: 'Spider-Man: Across the Spider-Verse',
      overview: 'Miles Morales is catapulted across the Multiverse, where he encounters a team of Spider-People charged with protecting its very existence.',
      posterPath: 'https://image.tmdb.org/t/p/w500/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg',
      backdropPath: 'https://image.tmdb.org/t/p/original/4Hod2vLwbv44O6mR1g85G4b6WWhE.jpg',
      voteAverage: 8.4,
      releaseDate: '2023-06-02',
      genres: ['Animation', 'Action', 'Adventure'],
      runtime: 140,
      status: 'Released',
    ),
  ];

  static final List<MovieModel> upcomingMovies = [
    const MovieModel(
      id: 201,
      title: 'Deadpool & Wolverine',
      overview: 'Wolverine is recovering from his injuries when he crosses paths with the loudmouth Deadpool.',
      posterPath: 'https://image.tmdb.org/t/p/w500/8cdWjvZQUX8iLFeL6aR4w7H5t4b.jpg',
      backdropPath: 'https://image.tmdb.org/t/p/original/dvBCdCohwWbsP5qAaglOXagDMtk.jpg',
      voteAverage: 7.9,
      releaseDate: '2026-07-26',
      genres: ['Action', 'Comedy', 'Sci-Fi'],
    ),
    const MovieModel(
      id: 202,
      title: 'Gladiator II',
      overview: 'Years after witnessing the death of Maximus, Lucius enters the Colosseum after his home is conquered.',
      posterPath: 'https://image.tmdb.org/t/p/w500/tOqIwliWMovSIZ9DyvHcHI7p2im.jpg',
      backdropPath: 'https://image.tmdb.org/t/p/original/euYIwmwkmz95mnXvufEmbL6ovhZ.jpg',
      voteAverage: 7.5,
      releaseDate: '2026-11-22',
      genres: ['Action', 'Drama', 'Adventure'],
    ),
    const MovieModel(
      id: 203,
      title: 'Inside Out 2',
      overview: 'Joy, Sadness, Anger, Fear and Disgust, who’ve been running a successful operation by all accounts, aren’t sure how to feel when Anxiety shows up.',
      posterPath: 'https://image.tmdb.org/t/p/w500/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg',
      backdropPath: 'https://image.tmdb.org/t/p/original/xg27NrXi7VXCGUr7MG75UqLl6Vg.jpg',
      voteAverage: 7.6,
      releaseDate: '2024-06-14',
      genres: ['Animation', 'Family', 'Comedy', 'Drama'],
    ),
  ];
}
